sudo:
  - false
language:
  - python
os:
  - linux
python:
  - '2.7'
  - '3.6'
cache:
  - pip
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=docdetect
after_success:
  - codecov
deploy:
  on:
    branch: master
    python: '3.6'
  provider: pypi
  user: ${PYPI_USER}
  password: ${PYPI_PWD}
  distributions: 'sdist bdist_wheel'
  skip_existing: true